sudo: required
language: node_js
node_js:
- node
services:
- docker
dist: trusty
branches:
  only:
  - master
  - develop
before_install:
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
- docker build -t eepmoody/open5e-api-beta .
- docker push eepmoody/open5e-api-beta
- docker tag eepmoody/open5e-api-beta registry.heroku.com/open5e-api-beta/web

deploy:
  provider: script
  script: 
  - docker push registry.heroku.com/open5e-api-beta/web
  - heroku container:release web -a open5e-api-beta
  on:
    branch: master
  api_key:
    secure: XT/6aiNfeLTwGWJXvwDgLEsbd+FLcDRAojrlod+bRb7FxvkEnjjZI9tswKVpc3lFudgNQy+uGtVmocajRCRVenkYklpeQQBB3C7KJukz04UpGdntzpS0ITpc3i3BUbtKKTSO72aDSPSR6q8ypXxeI1BTxHJ3tHVtnNGjzC//3v2tXHpGgSsAMWXEGQpZkCEPJHFj7NOXIEyOKHumm8ggt7eZv2LNg5r8x0DeLfrdUts7K7HbORliKeF+FwSU1lSFKWcKF1ngZbxgnd4PTfpePpXZfx3iv8CpIpVErq6B7VmCHw07j8OlTkRaiMteXp0anN3X9a9lFAbB/cV1tMfDeElyzJ/Gp1N3+MOMu9odmxzcAa/J1MW56styrbW9xsIu05YS8zxWX5czzO0scydwNZ+FqisnomiwvRyFBd0Co5w6Cy2tRyrH4hx6YNW4fdzMVgdAxo4t6uYp0kwS/VXragSucifOBDxRr7MYXXqXd2H4qib+GVQap77zg+eWAhgsxcNY108h+iwn6IcKgUDJweRhpPSfM6cFogYfDPGByhvhVEOW+ytWcvWWOpfVVqpXGJS+yBQCTD79Q74PsOKumhN9beP3ENczKf6mZG5mZ51N39P9W17E4JW6vz+VfmT4gdD6iuDIt+ZGyf2AK/Et99NZGbOqgTVX7U1ERXCPkO8=
