version: '3'
services:
  server:
    build: .
    environment:
      - OPEN5E_DEBUG=${OPEN5E_DEBUG}
      - 'SECRET_KEY=${SECRET_KEY}'
      - 'SERVER_NAME=${SERVER_NAME}'
      - 'CERTFILE=${CERTFILE}'
      - 'KEYFILE=${KEYFILE}'
    ports:
      - '443:8888'
    volumes:
      - .:/usr/src/open5e-api/

